### ISSUE TITLE
Zone.Identifier Stripping

### ISSUE THREAD

**Issue by slinkstr** [ViRb3/RunInTray#1]
I was curious what the point of the program copying itself and deleting the Zone.Identifier was (assuming you remember on such an old project). It doesn't seem to affect the function if I remove the Install and Unblock methods, compile, upload, and then download it from a GitHub release.

**Comment by ViRb3** [comment]
Zone Identifier is the "quarantine" flag for Windows. It's applied on files downloaded from the internet. If you try to run a program with this flag, you will either get a Smart screen prompt every time or the program will be blocked altogether. I believe the latter was the case when I first released this app, so I added the flag clear functionality to work aound it.
